# tree.py - Decision tree structure for medieval medical diagnosis

decisionTree = {
    "root": {
        "question": "Are you experiencing any of the following ailments: fever, cough, shortness of breath, or fatigue?",
        "fever": "fever",
        "cough": "cough",
        "shortness_of_breath": "shortness_of_breath",
        "fatigue": "fatigue",
        "none": "age",
    },
    "fever": {
        "question": "Is your fever above the temperature of boiling milk?",
        "yes": "high_fever",
        "no": "low_fever",
    },
    "cough": {
        "question": "Does thy cough persist from sunrise to sunset?",
        "yes": "persistent_cough",
        "no": "mild_cough",
    },
    "high_fever": {
        "question": "Doth thy heart race like a galloping steed, or do thy bones rattle with chills?",
        "yes": "flu_like_symptoms",
        "no": "common_cold",
    },
    "low_fever": {
        "question": "Is thy throat aflame or doth a mild cough trouble thee?",
        "yes": "upper_respiratory_infection",
        "no": "mild_viral_infection",
    },
    "persistent_cough": {
        "question": "Is thy chest wracked with pain or doth thy breathing wheeze like bellows?",
        "yes": "serious_respiratory_condition",
        "no": "upper_respiratory_infection",
    },
    "mild_cough": {
        "question": "Doth thy condition improve with the passing of days?",
        "yes": "recovering_mild_cough",
        "no": "monitor_for_changes",
    },
    "flu_like_symptoms": {
        "question": "Doth thy muscles ache as if after a joust, or is thy body wracked with pain?",
        "yes": "influenza",
        "no": "viral_infection",
    },
    "common_cold": {
        "question": "Doth thy nose run like a spring stream or is thy skull filled with congestion?",
        "yes": "common_cold_diagnosis",
        "no": "mild_infection",
    },
    "shortness_of_breath": {
        "question": "Doth thy chest feel as if crushed by a knight's armor or tightened by invisible bindings?",
        "yes": "serious_respiratory_issue",
        "no": "mild_breathing_issue",
    },
    "serious_respiratory_issue": {
        "question": "Hast thou been exposed to foul miasmas or allergens from foreign lands recently?",
        "yes": "allergic_reaction_or_asthma",
        "no": "potential_respiratory_infection",
    },
    "fatigue": {
        "question": "Is thy weariness accompanied by spinning visions or fainting spells?",
        "yes": "serious_cardiovascular_issue",
        "no": "general_fatigue",
    },
    "serious_cardiovascular_issue": {
        "question": "Doth thy family lineage carry the curse of weak heart or high blood pressure?",
        "yes": "cardiovascular_condition",
        "no": "investigate_further",
    },
    "age": {
        "question": "How many winters hast thou seen in this mortal realm?",
        "<10": "weight_child",
        "10-18": "weight_teen",
        "18-50": "gender",
        ">50": "older_adult",
    },
    "weight_child": {
        "question": "What is thy weight in stone?",
        "low_weight": "low_weight_child",
        "normal_weight": "normal_weight_child",
        "high_weight": "high_weight_child",
    },
    "weight_teen": {
        "question": "What is thy weight in stone?",
        "low_weight": "low_weight_teen",
        "normal_weight": "normal_weight_teen",
        "high_weight": "high_weight_teen",
    },
    "gender": {
        "question": "Art thou a lord or a lady?",
        "male": "adult_male",
        "female": "pregnancy",
    },
    "pregnancy": {
        "question": "Art thou with child or experiencing thy monthly blood?",
        "pregnant": "pregnancy_condition",
        "menstruating": "menstruation",
        "no": "adult_female",
    },
    "pregnancy_condition": {
        "question": "Doth thy belly ache or dost thou experience unusual symptoms of concern?",
        "yes": "potential_pregnancy_complication",
        "no": "normal_pregnancy",
    },
    "menstruation": {
        "question": "Is thy flow heavier than a river after the spring rains, or thy cramps as painful as a knight's lance?",
        "yes": "severe_menstruation",
        "no": "normal_menstruation",
    },
    "older_adult": {
        "question": "Dost thou suffer from conditions of the humors such as sugar sickness, heart weakness, or blood pressure of unnatural height?",
        "yes": "chronic_condition",
        "no": "healthy_older_adult",
    },
    # Medieval diagnoses
    "common_cold_diagnosis": "the common affliction of catarrh",
    "mild_infection": "a slight imbalance of the humors",
    "influenza": "the sweating sickness",
    "viral_infection": "a pestilence of minor concern",
    "upper_respiratory_infection": "an inflammation of the breathing passages",
    "mild_viral_infection": "a minor pestilence of the body",
    "serious_respiratory_condition": "the consumption",
    "recovering_mild_cough": "a passing affliction of the lungs",
    "monitor_for_changes": "an uncertain malady requiring observation",
    "allergic_reaction_or_asthma": "the vapors affecting thy breathing",
    "potential_respiratory_infection": "a miasma in thy lungs",
    "mild_breathing_issue": "a slight hindrance to thy breath",
    "cardiovascular_condition": "an affliction of the life-giving organ",
    "investigate_further": "a mystery ailment requiring the wisdom of the royal physician",
    "general_fatigue": "a depletion of vital spirits",
    "low_weight_child": "a need for more hearty stews and meats",
    "normal_weight_child": "the proper constitution for a young one",
    "high_weight_child": "an abundance of humors causing excess weight",
    "low_weight_teen": "insufficient sustenance for thy growing form",
    "normal_weight_teen": "a balanced constitution befitting thy age",
    "high_weight_teen": "an excess of phlegmatic humor",
    "adult_male": "a condition common to men of thy station",
    "adult_female": "a condition befitting ladies of the court",
    "potential_pregnancy_complication": "a concerning state that may affect thy unborn child",
    "normal_pregnancy": "the natural condition of bearing new life",
    "severe_menstruation": "an excess of blood humor requiring herbal remedies",
    "normal_menstruation": "the natural monthly purge of excess blood",
    "chronic_condition": "a long-standing imbalance of the four humors",
    "healthy_older_adult": "the natural aging of thy mortal vessel",
}